import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ReactLenis } from "@/utils/lenis";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Component from lenis/react */}
      <ReactLenis root>
        <body className={inter.className}>{children}</body>
      </ReactLenis>
    </html>
  );
}
